let products = [
  {
    id: 1,
    title: "Realme C65",
    price: 6000,
    category: "Phones",
    imageUrl: "imgs/phones/realmeC65.jpg",
  },
  {
    id: 2,
    title: "Samsung A55",
    price: 20000,
    category: "Phones",
    imageUrl: "imgs/phones/samsungA55.jpg",
  },
  {
    id: 3,
    title: "Joyroom airpods",
    price: 1000,
    category: "Phone accessories",
    imageUrl: "imgs/phone-accessories/joyroom.jpg",
  },
  {
    id: 4,
    title: "Samsung A52",
    price: 15000,
    category: "Phones",
    imageUrl: "imgs/phones/samsungA52.jpg",
  },
  {
    id: 5,
    title: "Apple airpods",
    price: 5000,
    category: "Phone accessories",
    imageUrl: "imgs/phone-accessories/apple-airpods.jpg",
  },
  {
    id: 6,
    title: "Iphone 15",
    price: 35000,
    category: "Phones",
    imageUrl: "imgs/phones/iphone15.jpg",
  },
  {
    id: 7,
    title: "Charger",
    price: 300,
    category: "Phones",
    imageUrl: "imgs/phone-accessories/charger.jpg",
  },
  {
    id: 8,
    title: "Jacket",
    price: 1000,
    category: "Fashion",
    imageUrl: "imgs/fashion/jacket.jpg",
  },
  {
    id: 9,
    title: "Hoodie",
    price: 800,
    category: "Fashion",
    imageUrl: "imgs/fashion/hoodie.jpeg",
  },
  {
    id: 10,
    title: "T-shirt",
    price: 500,
    category: "Fashion",
    imageUrl: "imgs/fashion/t-shirt.jpg",
  },
  {
    id: 11,
    title: "Coat",
    price: 2000,
    category: "Fashion",
    imageUrl: "imgs/fashion/coat.jpeg",
  },
  {
    id: 12,
    title: "Adidas Shoes",
    price: 1000,
    category: "Fashion",
    imageUrl: "imgs/fashion/adidas.jpg",
  },
  {
    id: 13,
    title: "Shoes",
    price: 400,
    category: "Fashion",
    imageUrl: "imgs/fashion/shoes.jpg",
  },
  {
    id: 14,
    title: "Pantalon",
    price: 600,
    category: "Fashion",
    imageUrl: "imgs/fashion/pantalon.jpeg",
  },
  {
    id: 15,
    title: "Pantalon",
    price: 800,
    category: "Fashion",
    imageUrl: "imgs/fashion/pantalon2.jpeg",
  },
  {
    id: 16,
    title: "Scarf",
    price: 200,
    category: "Fashion",
    imageUrl: "imgs/fashion/scarf.jpeg",
  },
];
